# GoReleaser configuration for alpha releases (v2.0.0-alpha.*)
# This generates aurl-v2-alpha formula that installs the binary as "aurl-v2-alpha"

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: aurl-v2-alpha
    # Always upload alpha releases
    skip_upload: false

    # GitHub/GitLab repository to push the formula to
    repository:
      owner: classmethod
      name: homebrew-repos

    # Git author used to commit to the repository
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

    # Commit message template
    commit_msg_template: "Brew formula update for {{ .ProjectName }} alpha version {{ .Tag }}"

    # Directory inside the repository to put the formula
    directory: Formula

    # Homepage of the project
    homepage: "https://github.com/classmethod/aurl"

    # Description of the project
    description: "URL Command Line Tool with Authentication Support (v2 alpha build)"

    # Install binary with v2-alpha suffix to avoid conflicts
    install: |
      bin.install "aurl" => "aurl-v2-alpha"

    # Test script for brew
    test: |
      system "#{bin}/aurl-v2-alpha --version"

    # Add conflicts_with to prevent installing both stable and alpha
    custom_block: |
      conflicts_with "aurl", because: "both install similar binaries"

# modelines, feel free to remove those if you don't want/use them:
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
